global:
  scrape_interval: 15s # 데이터 모집 인터벌
  evaluation_interval: 15s # 데이터 모집 인터벌

scrape_configs:
  - job_name: "monitoring"
    
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django"
    static_configs:
      - targets: ["django:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]